default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: fin_app_production
  username: fin-app
  password: <%= ENV["RENDER_DEPLOY_DATABASE_PASSWORD"]%>
  